name: Read Azure Flag

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  read-flag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Read blob and output flag
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob download \
              --account-name iamazurelab3f69ef6de \
              --container-name flag \
              --name flag.txt \
              --file flag.txt \
              --auth-mode login
            echo "===== FLAG ====="
            cat flag.txt
